export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';

export const OPEN_SIDEBAR = 'OPEN_SIDEBAR';
export const CLOSE_SIDEBAR = 'CLOSE_SIDEBAR';

export const SET_EDU_FORMS = 'SET_EDU_FORMS';
export const SET_DIRECTION_TYPES = 'SET_DIRECTION_TYPES';
export const SET_DISTRIBUTION_TYPES = 'SET_DISTRIBUTION_TYPES';

export const DIALOG_QUESTION_OPEN = 'DIALOG_QUESTION_OPEN';
export const DIALOG_QUESTION_CLOSE = 'DIALOG_QUESTION_CLOSE';

export const FETCHING_START = 'FETCHING_START';
export const FETCHING_END = 'FETCHING_END';

export const SET_EMPLOYMENT_LIST = 'SET_EMPLOYMENT_LIST';
export const SET_EMPLOYMENT_LIST_SORTING = 'SET_EMPLOYMENT_LIST_SORTING';
export const DELETE_EMPLOYMENT = 'DELETE_EMPLOYMENT';
export const SET_EMPLOYMENT_SUGGESTIONS = 'SET_EMPLOYMENT_SUGGESTIONS';
export const CLEAR_EMPLOYMENT_SUGGESTIONS = 'CLEAR_EMPLOYMENT_SUGGESTIONS';
