export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';

export const OPEN_SIDEBAR = 'OPEN_SIDEBAR';
export const CLOSE_SIDEBAR = 'CLOSE_SIDEBAR';

export const SET_EDU_FORMS = 'SET_EDU_FORMS';
export const SET_DIRECTION_TYPES = 'SET_DIRECTION_TYPES';
export const SET_DISTRIBUTION_TYPES = 'SET_DISTRIBUTION_TYPES';

export const DIALOG_QUESTION_OPEN = 'DIALOG_QUESTION_OPEN';
export const DIALOG_QUESTION_CLOSE = 'DIALOG_QUESTION_CLOSE';
