export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';

export const OPEN_SIDEBAR = 'OPEN_SIDEBAR';
export const CLOSE_SIDEBAR = 'CLOSE_SIDEBAR';

export const SET_EDU_FORMS = 'SET_EDU_FORMS';
export const SET_DIRECTION_TYPES = 'SET_DIRECTION_TYPES';
export const SET_DISTRIBUTION_TYPES = 'SET_DISTRIBUTION_TYPES';

export const DIALOG_QUESTION_OPEN = 'DIALOG_QUESTION_OPEN';
export const DIALOG_QUESTION_CLOSE = 'DIALOG_QUESTION_CLOSE';

export const FETCHING_START = 'FETCHING_START';
export const FETCHING_END = 'FETCHING_END';

export const SET_EMPLOYMENT_LIST = 'SET_EMPLOYMENT_LIST';
export const SET_EMPLOYMENT_LIST_SORTING = 'SET_EMPLOYMENT_LIST_SORTING';
export const DELETE_EMPLOYMENT = 'DELETE_EMPLOYMENT';
export const SET_EMPLOYMENT_SUGGESTIONS = 'SET_EMPLOYMENT_SUGGESTIONS';
export const CLEAR_EMPLOYMENT_SUGGESTIONS = 'CLEAR_EMPLOYMENT_SUGGESTIONS';

export const SET_ORGANIZATION_LIST = 'SET_ORGANIZATION_LIST';
export const SET_ORGANIZATION_LIST_SORTING = 'SET_ORGANIZATION_LIST_SORTING';
export const DELETE_ORGANIZATION = 'DELETE_ORGANIZATION';
export const SET_ORGANIZATION_SUGGESTIONS = 'SET_ORGANIZATION_SUGGESTIONS';
export const CLEAR_ORGANIZATION_SUGGESTIONS = 'CLEAR_ORGANIZATION_SUGGESTIONS';

export const SET_COUNRIES_SUGGESTIONS = 'SET_COUNRIES_SUGGESTIONS';
export const CLEAR_COUNRIES_SUGGESTIONS = 'CLEAR_COUNRIES_SUGGESTIONS';
export const SET_ADDRESSES_SUGGESTIONS = 'SET_ADDRESSES_SUGGESTIONS';
export const CLEAR_ADDRESSES_SUGGESTIONS = 'CLEAR_ADDRESSES_SUGGESTIONS';

export const SET_STUDENTS_SELECTION = 'SET_STUDENTS_SELECTION';
export const CLEAR_STUDENTS_SELECTION = 'CLEAR_STUDENTS_SELECTION';
export const OPEN_STUDENTS_SELECTION = 'OPEN_STUDENTS_SELECTION';
export const CLOSE_STUDENTS_SELECTION = 'CLOSE_STUDENTS_SELECTION';

export const SET_SPECIALITIES_SUGGESTIONS = 'SET_SPECIALITIES_SUGGESTIONS';
export const CLEAR_SPECIALITIES_SUGGESTIONS = 'CLEAR_SPECIALITIES_SUGGESTIONS';
export const SET_EMPLOYMENT_CONTRACT = 'SET_EMPLOYMENT_CONTRACT';
export const SET_SCHOOLS_SUGGESTIONS = 'SET_SCHOOLS_SUGGESTIONS';
export const CLEAR_SCHOOLS_SUGGESTIONS = 'CLEAR_SCHOOLS_SUGGESTIONS';
export const SET_ORGANIZATIONS_SUGGESTIONS = 'SET_ORGANIZATIONS_SUGGESTIONS';
export const CLEAR_ORGANIZATIONS_SUGGESTIONS = 'CLEAR_ORGANIZATIONS_SUGGESTIONS';
